
DROP TABLE IF EXISTS INSURANCES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE INSURANCES(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
);

CREATE TABLE USERS(
	ID INT AUTO_INCREMENT,
	USER_NAME VARCHAR(255),
	PASS VARCHAR(255),
	NAME VARCHAR(255),
	SUR_NAME VARCHAR(255),
	USER_JMBG VARCHAR(255),
	PASSPORT_NUMBER VARCHAR(255),
	ADDRESS VARCHAR(255),
	PHONE VARCHAR(255),
	EMAIL VARCHAR(255)
);